#!/bin/bash

######################################################################
#
#  Copyright (c) 2015 arakasi72 (https://github.com/arakasi72)
#
#  --> Licensed under the MIT license: http://www.opensource.org/licenses/mit-license.php
#
######################################################################

rundir=$(dirname $(readlink -f $0))

if [ "$(id -u)" != "0" ]; then
  echo "Must be run as root, directly or with sudo"
  exit 1
fi

# kill apt-daily.service if running 
if [[ $(systemctl list-units --all apt-daily.service | fgrep -c apt-daily.service) -gt 0 ]]; then
  systemctl stop apt-daily.service > /dev/null 2>&1
  systemctl kill --kill-who=all apt-daily.service > /dev/null 2>&1
  sleep 5
fi

if [ $(dpkg-query -W -f='${Status}' git 2>/dev/null | grep -c "ok installed") -eq 0 ]; then
apt-get -qq update
echo "Installing git"
apt-get -yqq install git 2>&1 >> /dev/null
fi

if [ $(dpkg-query -W -f='${Status}' ca-certificates 2>/dev/null | grep -c "ok installed") -eq 0 ]; then
apt-get -qq update
echo "Installing ca-certificates"
apt-get -yqq install ca-certificates 2>&1 >> /dev/null
fi

echo "Installing rtinst"
cd
rm -fr /etc/rtinst
git clone https://github.com/stickz/rtinst.git /etc/rtinst
cd /etc/rtinst
git checkout master
cd
ln -sf /etc/rtinst/scripts/* /usr/local/bin
ln -sf /etc/rtinst/rtsetup /usr/local/bin

echo "Installation complete"
echo
echo "You can now run rtinst and the additional supporting scripts"

if [ "$rundir" != "/etc/rtinst" ]; then
    rm -f $rundir/rtsetup
fi
